name: Sennerlov
favicon: null
layout_spectrum: 0.4724541073665023
typography_spectrum: 0.09985185391269624
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4762028076220304
  lightness: 0.562632312066853
  saturation: 0.9258723047096282
  rhythmicContrast: 0.3517725230194628
purpose: []
